# Generated by Django 4.0 on 2022-01-18 21:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500, unique=True)),
                ('photo', models.ImageField(null=True, upload_to='places/')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='places.location')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.IntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500, unique=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('details', models.TextField(max_length=1000, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.scheduleday')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceTagged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.place')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=8)),
                ('details', models.TextField(max_length=1000, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.place')),
            ],
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='location_latitude_longitude_key'),
        ),
        migrations.AddConstraint(
            model_name='scheduletime',
            constraint=models.UniqueConstraint(fields=('day', 'start', 'end'), name='schedule_time_day_start_end_key'),
        ),
        migrations.AddConstraint(
            model_name='scheduleday',
            constraint=models.UniqueConstraint(fields=('place', 'day_index'), name='scheduleday_place_day_index_key'),
        ),
        migrations.AddConstraint(
            model_name='placetagged',
            constraint=models.UniqueConstraint(fields=('place', 'tag'), name='placetagged_place_tag_key'),
        ),
        migrations.AddConstraint(
            model_name='phone',
            constraint=models.UniqueConstraint(fields=('place', 'phone'), name='phone_place_phone_key'),
        ),
    ]
