# Generated by Django 4.0 on 2022-01-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField()),
                ('field_type', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=5000)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.editor')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('photo', models.CharField(max_length=1000, null=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.editor')),
            ],
        ),
    ]
