# Generated by Django 4.0 on 2022-01-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_synonyms_synonym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='name',
            field=models.TextField(max_length=500),
        ),
    ]
