# Generated by Django 4.0 on 2022-01-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_rename_synonym_placesynonym_tagsynonym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsynonym',
            name='tag',
        ),
        migrations.DeleteModel(
            name='PlaceSynonym',
        ),
        migrations.DeleteModel(
            name='TagSynonym',
        ),
    ]
