# Generated by Django 4.0 on 2022-02-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_contact_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='contact',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
