# Generated by Django 4.0 on 2022-01-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='index',
            field=models.IntegerField(unique=True),
        ),
    ]
