# Generated by Django 4.0 on 2022-02-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='contact',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
