# Generated by Django 4.0 on 2022-02-28 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_good_query', models.BooleanField(null=True)),
                ('user', models.BigIntegerField(null=True)),
            ],
        ),
    ]
