# Generated by Django 4.0 on 2022-01-30 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500, unique=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('contact', models.TextField(max_length=1000, null=True)),
                ('schedule', models.TextField(max_length=1000, null=True)),
                ('photo', models.ImageField(null=True, upload_to='places/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceTagged',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='places.place')),
                ('tag', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='places.tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('latitude__isnull', False), ('longitude__isnull', False)), models.Q(
                ('latitude__isnull', True), ('longitude__isnull', True)), _connector='OR'), name='place_partial_location_not_allowed'),
        ),
        migrations.AddConstraint(
            model_name='placetagged',
            constraint=models.UniqueConstraint(
                fields=('place', 'tag'), name='placetagged_place_tag_key'),
        ),
    ]
