# Generated by Django 4.0 on 2022-02-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='place',
        ),
        migrations.RemoveField(
            model_name='place',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='place',
            name='schedule',
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.DeleteModel(
            name='Addition',
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
