# Generated by Django 4.0 on 2022-02-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='page',
            name='page_id_type_unique',
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
