# Generated by Django 4.0 on 2022-02-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='route',
            name='source',
        ),
        migrations.RemoveField(
            model_name='route',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='route',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='route',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
