# Generated by Django 4.0 on 2022-01-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
