# Generated by Django 4.0 on 2022-01-29 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.IntegerField(unique=True)),
                ('title', models.TextField(max_length=500)),
                ('pub_date', models.DateTimeField()),
                ('author', models.TextField(max_length=100)),
                ('link', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('index', models.IntegerField()),
                ('category', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTagged',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='news.article')),
                ('tag', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='news.tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='articletagged',
            constraint=models.UniqueConstraint(
                fields=('article', 'tag'), name='articletagged_article_tag_key'),
        ),
    ]
