# Generated by Django 4.0 on 2022-01-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
