# Generated by Django 4.0 on 2022-01-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tutorials.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tutorials.course'),
            preserve_default=False,
        ),
    ]
