# Generated by Django 4.0 on 2022-01-25 02:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TextField(max_length=100)),
                ('end', models.TextField(max_length=100)),
                ('price', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='StartTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelStartPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000, unique=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.bustravel')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.day')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.travelstartpoint')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.starttime')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.bustravel')),
            ],
        ),
    ]
