# Generated by Django 4.0 on 2022-01-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustravel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
