# Generated by Django 4.0 on 2022-01-25 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_bustravel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TextField(max_length=100)),
                ('end', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.traveltype')),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.travel'),
        ),
        migrations.AlterField(
            model_name='travelstartpoint',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transport.travel'),
        ),
        migrations.DeleteModel(
            name='BusTravel',
        ),
    ]
