# Generated by Django 4.0 on 2022-01-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_traveltype_travel_alter_schedule_travel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelstartpoint',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='travelstartpoint',
            constraint=models.UniqueConstraint(fields=('description', 'travel'), name='travelstartpoint_description_travel_key'),
        ),
    ]
