# Generated by Django 4.0 on 2022-01-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_travelstartpoint_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day',
            new_name='ScheduleDay',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='StartTime',
        ),
    ]
