# Generated by Django 4.0 on 2022-02-01 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('surname', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=500)),
                ('phone', models.TextField(max_length=100)),
                ('href', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Ty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitTy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True)),
                ('url', models.TextField(max_length=1000)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='directory.location')),
                ('ty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='directory.unitty')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='directory.unit')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='directory.function')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='directory.person')),
                ('ty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='directory.ty')),
            ],
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('person', 'department', 'ty', 'function'), name='role_person_department_ty_function_key'),
        ),
    ]
