# Generated by Django 4.0 on 2022-02-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTy',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_function', models.BooleanField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='role_person_department_ty_function_key',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='department',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='url',
            new_name='href',
        ),
        migrations.RemoveField(
            model_name='role',
            name='function',
        ),
        migrations.RemoveField(
            model_name='role',
            name='ty',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='location',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='ty',
        ),
        migrations.AddField(
            model_name='location',
            name='href',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Function',
        ),
        migrations.DeleteModel(
            name='UnitTy',
        ),
        migrations.AddField(
            model_name='rolety',
            name='role',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to='directory.role'),
        ),
        migrations.AddField(
            model_name='rolety',
            name='ty',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to='directory.ty'),
        ),
    ]
